### ISSUE TITLE
[tuify] Use offscreen buffer from r3bl_tui to make repaints smooth

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#118]
Context:
- Crate: https://crates.io/crates/r3bl_tuify
- Repo: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/tuify

The `r3bl_tui` crate uses `OffscreenBuffer` as a way to massively increase the performance of terminal repainting. 

- Docs: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/tui#offscreen-buffer
- Source code: https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tui/src/tui/terminal_lib_backends/offscreen_buffer.rs#L36

Use the `OffscreenBuffer` in `r3bl_tuify` to make repainting really fast. And w/ all this extra headroom for performance use lolcat and other enhanced styling for rendering the selection and non selection (all of these can be found in the `r3bl_tui` crate). For ex, we can not only use interesting emoji and other [ANSI glpyhs](https://github.com/r3bl-org/r3bl-ts-utils/blob/main/src/tui-figures/symbols.ts), we can also use gradient color foregrounds and background much like you see in the `r3bl_tui` crate. 

Here are some videos to illustrate:

![](https://user-images.githubusercontent.com/2966499/234949476-98ad595a-3b72-497f-8056-84b6acda80e2.gif)

![](https://user-images.githubusercontent.com/2966499/233799311-210b887e-0aa6-470a-bcea-ee8e0e3eb019.gif)

**Comment by johnmcl001** [comment]
I can take a look at this.

**Comment by nazmulidris** [comment]
This issue is open for anyone to work on.

**Comment by nazmulidris** [comment]
@e0lithic Please let me know if you have any questions about this one.

**Comment by johnmcl001** [comment]
@nazmulidris Apologies for disappearing for 3 weeks, personal stuff came up 😞.

**Comment by nazmulidris** [comment]
@johnmcl001 Oh no, I hope you are doing well. Whenever you have opportunity & time & motivation, you are most welcome to start contributing again! ❤️

**Comment by e0lithic** [comment]
**Overview:**
- Exploration of a solution involving an inline buffer encountered challenges, particularly related to terminal resizing.

**Considered Solution:**
- Created a buffer matching the required viewport dimensions.
- Determined the buffer position in the terminal and printed it at this offset.

**Constraints:**
- Major issues emerged during terminal resizing.
- Inconsistent behaviors across different emulators, even in windowed and maximized modes.
- Difficulty in reconciling diverse behaviors for all potential terminals.

**Possible Workarounds:**
- Contemplated capturing the entire screen as a potential workaround.
- Acknowledged that this approach falls within the domain of tui and is currently out of scope for the existing library.

**Comment by nazmulidris** [comment]
@e0lithic Thank you so much for capturing this context. This has been a great area of exploration for our core technology. And thank you for leading the charge in this arena and heading into the unknown to see how far we can push this thing! Kudos! 🎉 

This is an excellent first PR for someone who is new to TUI and Rust! 👏🏽 🚀 
https://github.com/r3bl-org/r3bl-open-core/pull/203

And thank you for bringing light to the resize issue. We have a fix here but it is limited in what we can achieve due to terminal restrictions.

https://github.com/r3bl-org/r3bl-open-core/commit/26a3609cc1cb6d8be7ab228203ae3b03b5b23857
