### ISSUE TITLE
Add support for display and selecting across multiple columns

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#119]
Context:
- Crate: https://crates.io/crates/r3bl_tuify
- Repo: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/tuify

Currently only a single column of items `Vec<String>` is supported. Multiple or single selection is supported.

However, multiple columns are not supported. In addition to providing the max height of the tuify select area, also provide the max number of columns. And allow caret movement not just up and down, but also left and right. Similarly, support multiple selection semantics as well.

This functionality could be added by using flexbox layout manager from `r3bl_tui`. Here are some links:
- https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tui/src/tui/layout/flex_box.rs#L1

**Comment by e0lithic** [comment]
May I take a shot at it.

**Comment by nazmulidris** [comment]
@e0lithic This is all yours. Something that might help make this simpler is working on this issue first: https://github.com/r3bl-org/r3bl_rs_utils/issues/118

**Comment by e0lithic** [comment]
> @e0lithic This is all yours. Something that might help make this simpler is working on this issue first: #118

Sure, I will go through #118 first then.

**Comment by nazmulidris** [comment]
@e0lithic Over the weekend, I will take some more time to elaborate on this issue w/ code examples, etc. Sorry that the description is rather vague

**Comment by nazmulidris** [comment]
@e0lithic If you have any questions about #118 please let me know as well. We can also chat on discord https://discord.gg/8M2ePAevaM if that is easier.

**Comment by nazmulidris** [comment]
@e0lithic I will unassign you from this issue since you're added to #118 already 👍🏽

**Comment by e0lithic** [comment]
Sure
