### ISSUE TITLE
r3bl_ansi_color - add support for syntect output

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#125]
Context:
- Repo: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/ansi_color
- Crate: https://crates.io/crates/r3bl_ansi_color

Provide a syntect theme & make it easy to take output from syntect and use this crate to colorize it before it is printed to the terminal

Functionality to do this already exists int he `r3bl_tui` crate here https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tui/src/tui/syntax_highlighting/r3bl_syntect_theme.rs#L1

**Comment by LuciAkirami** [comment]
Hey @nazmulidris , I would like to try this, but not exactly sure where to start. So I want to know where exactly would the syntect fit in?. I mean like does it go as a variable to the struct AnsiStyledText(like modify the struct to also take in a theme?) ? And we highlight the text before applying the styles(bold, italic, font color) right?

**Comment by nazmulidris** [comment]
@LuciAkirami I just assigned you to this issue. 

The intention behind this issue is to provide an easy way for someone who wants to use the `syntect` crate to be able to use this crate.

So basically the idea is to take this:

https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tui/src/tui/syntax_highlighting/syntect_to_styled_text_conversion.rs#L64

and make a version of it that works with this crate `AnsiStyledText` is the output.
