### ISSUE TITLE
Add tests for existing `ansi_color` functionality

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#135]
[`ansi_color` folder](https://github.com/r3bl-org/r3bl-open-core/tree/main/ansi_color)

**Comment by trkelly23** [comment]
I grabbed this issue and wanted to get some early feedback hence the draft PR.  It's usually easier in the PR format.  Please take a look as time allows.  No rush!

**Comment by nazmulidris** [comment]
@trkelly23 Just assigned the issue to you. Thanks for sharing the draft PR. We will take a look at this week.
