### ISSUE TITLE
[tui] editor component - write lots of tests for new features that got added

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#184]
Add tests for 
- [ ] select, 
- [ ] copy, 
- [ ] cut, 
- [ ] paste, 
- [ ] delete, 
- [ ] undo, 
- [ ] redo

**Comment by e0lithic** [comment]
> Add tests for
> 
> * [ ]  select,
> * [ ]  copy,
> * [ ]  cut,
> * [ ]  paste,
> * [x]  delete,
> * [ ]  undo,
> * [ ]  redo

Running status of testcases.

**Comment by e0lithic** [comment]
Running Status for testcases : 

> * [ ]  select,
> * [ ]  copy,
> * [ ]  cut,
> * [ ]  paste,
> * [x]  delete,
> * [x]  backspace,
> * [ ]  undo,
> * [ ]  redo

**Comment by e0lithic** [comment]
Running status for Test-cases :

* [ ]  select
* [ ]  copy
* [ ]  cut
* [ ]  paste
* [ ]  delete
* [ ] backspace
* [ ]  undo
* [ ]  redo
