### ISSUE TITLE
[tui] Markdown parser doesn't render correctly with `#` after all formats

### ISSUE THREAD

**Issue by Harshil-Jani** [r3bl-org/r3bl-open-core#194]
**Platform** Arch Linux (w/ KDE , i3wm)
**Terminal software** Konsole

## Describe the problem you are observing.
Basically in markdown we have six heading styles with `#`. But, If you try to put in more hashes than 6, Then it has a weird behaviour. It cannot detect the space afterwards and does confuses the editor.

## Steps to reproduce
1. Open the file in tui.
1. Try to put >6  (Eg: 7) number of hashes and press space and write something.

## Screenshots/Screencaptures

https://github.com/r3bl-org/r3bl-open-core/assets/79367883/5609c67d-844e-4d0e-9dcd-1a9ca854f04f

Very helpful if the display doesn't seem to work

**Comment by nazmulidris** [comment]
@Harshil-Jani Good job finding this issue. I had randomly run into it before but wasn't able to repro it.
