### ISSUE TITLE
[tui, redux] Address performance issues

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#196]
Tracking issue to capture things related to performance issues (caret movements slow, redux cloning too much, color wheel gradients not memoized, etc). We can capture flamegraph results here or other testing results here and figure out how to address these solutions. 

One idea might be to radically simplify the architecture and remove redux + async + await / tokio.

Design document to work on: 
- https://docs.google.com/document/d/1OMB1rX6cUL_Jxpl-OUWMhJijM7c4FoDrK6qDViVXBWk/edit

Youtube video on this:
- https://youtu.be/o2CVEikbEAQ

**Comment by Harshil-Jani** [comment]
![flamegraph](https://github.com/r3bl-org/r3bl-open-core/assets/79367883/f9aae600-dc9c-4e94-9069-176851b4bed3)
 From the flamegraphs, Redux seems like the culprit for performance.
