### ISSUE TITLE
[tuify][design] Update the Tuify default design

### ISSUE THREAD

**Issue by NadiaIdris** [r3bl-org/r3bl-open-core#224]
# TODO 

1. Update the Tuify default design to appear more appealing.
2. Create few more styles that users can choose from out of the box.
3. Write a section in tuify README.md on how to choose default or few other pre-designed style for single and multi select components.
4. Make sure all the designs work on editors with light or dark theme.

## Current default designs

Single select default design

![Image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/e4a56a83-756a-489e-a666-c4b9a5a446e7)

Multiple select default design

![Image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/e178e202-5a05-4431-82fe-51736dacd661)

**Comment by NadiaIdris** [comment]
Idea for default design:
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/d60fee51-c532-47a3-baf2-c55e24e1a61c)

**Comment by NadiaIdris** [comment]
Idea for theme "Seaweed"
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/6ba0373c-c745-47ea-ab25-b40b04224e10)

**Comment by NadiaIdris** [comment]
Idea for hot pink
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/71f514b7-e29c-4ca1-a8b9-7d19268878bc)

**Comment by nazmulidris** [comment]
They're all amazing

**Comment by NadiaIdris** [comment]
Note: added a darker background color to all 3 styles to increase readability via contrast.

## Default style implemented in code (screenshot)

![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/36de726c-b8fe-41b8-a076-39c6418a17f9)

### Focused item is also the selected item
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/b7107de4-1f17-4905-bb4b-30cc484ff058)

## Sea foam style implemented in code (screenshot)

![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/dd46793b-4a80-4f73-bf92-637cfcdb5bd9)

### Focused item is also the selected item
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/8ec4be30-1344-4712-9912-e1191076c6ea)


## Hot pink style implemented in code (screenshot)

![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/5f371114-0723-4be6-9100-a3989d695495)

### Focused item is also the selected item
![image](https://github.com/r3bl-org/r3bl-open-core/assets/22040032/8e3403aa-987c-4210-9026-ef6affb847c4)
