### ISSUE TITLE
[feature request] ReadLineEvent support for terminal resizing

### ISSUE THREAD

**Issue by Cthutu** [r3bl-org/r3bl-open-core#321]
`Crossterm` supports sending events when the terminal resizes.  This is important for any program that needs to wrap text to a certain width, and the user changes the size of the terminal window during use.

My first question is: Does r3bl-terminal-async support notifications of terminal resizing?

If not, my second question is: Can we add a `ReadLineEvent` entry for terminal resizing?

This is stopping me from using your wonderful crate currently.  I plan to write a MUD game and I am looking for a crate that does asynchronous output while receiving input.

Thanks.

**Comment by nazmulidris** [comment]
@Cthutu Definitely. I can add a resize variant to `ReadlineEvent`. I will reply to you when I've added this (in a few hours).

I'd not envisioned people using this crate and controlling each "pixel" of the terminal viewport. The `r3bl_tui` crate is well suited for this use case. I don't know if you've had a chance to check that one out: https://docs.rs/r3bl_tui/latest/r3bl_tui/. (It is in the same mono repo as `r3bl_terminal_async`.

**Comment by nazmulidris** [comment]
@Cthutu I just made the changes you requested to v0.5.1. Here is the full changelog:
https://github.com/r3bl-org/r3bl-open-core/blob/main/CHANGELOG.md#v051-2024-04-28

PLMK if you have any questions about using the API or if you need any changes made. And please keep me posted on the game that you're building! 🎉

**Comment by nazmulidris** [comment]
@Cthutu If you haven't already, please checkout our YT channel here. There's an entire playlist on building the r3bl_terminal_async (roughly) from inception to release.

  - [Part 1: Why?](https://youtu.be/6LhVx0xM86c)
  - [Part 2: What?](https://youtu.be/3vQJguti02I)
  - [Part 3: Do the refactor and rename the crate](https://youtu.be/uxgyZzOmVIw)
  - [Part 4: Build the spinner](https://www.youtube.com/watch?v=fcb6rstRniI)
  - [Part 5: Add color gradient animation to spinner](https://www.youtube.com/watch?v=_QjsGDds270)
  - [Part 6: Publish the crate and overview](https://youtu.be/X5wDVaZENOo)
  - [Testing playlist](https://www.youtube.com/watch?v=Xt495QLrFFk&list=PLofhE49PEwmwLR_4Noa0dFOSPmSpIg_l8)
    - [Part 1: Intro](https://www.youtube.com/watch?v=Xt495QLrFFk)
    - [Part 2: Deep dive](https://www.youtube.com/watch?v=4iM9t5dgvU4)
  - Playlists
    - [Build with Naz, async readline and spinner for CLI in Rust](https://www.youtube.com/watch?v=3vQJguti02I&list=PLofhE49PEwmwelPkhfiqdFQ9IXnmGdnSE)
    - [Build with Naz, testing in Rust](https://www.youtube.com/watch?v=Xt495QLrFFk&list=PLofhE49PEwmwLR_4Noa0dFOSPmSpIg_l8)

**Comment by Cthutu** [comment]
I've started watching those videos - thanks for sharing your development experience.  And thanks so much for adding that feature in a timely matter!  It's really helpful.  Knowing how wide the terminal is means I can wrap text properly.  And those sneaky users can do it at runtime means I have to figure out what I will have to do when that happens.

**Comment by nazmulidris** [comment]
> I've started watching those videos - thanks for sharing your development experience. And thanks so much for adding that feature in a timely matter! It's really helpful. Knowing how wide the terminal is means I can wrap text properly. And those sneaky users can do it at runtime means I have to figure out what I will have to do when that happens.

@Cthutu Glad to hear you are taking a look at the videos. You're most welcome for the videos & new features! 🙏🏽 

I agree that terminal width is important to know, typically in raw mode, when you control all the "pixels" that are displayed, and you have some state containing what is supposed to have already been painted, then you can apply a strategy of clearing the display or affected lines and then repainting them. In r3bl_tui, thats what I do with the OffscreenBuffer. You might take a look at it to get some ideas. In your game, you might consider saving all the output that goes to SharedWriters to an intermediate buffer, so that you can repaint when you need.

**Comment by nazmulidris** [comment]
@Cthutu also we have a discord server, if you want to ask questions about the crate or other CLI / TUI topics: https://discord.gg/PhuF4qFpcA
